ejercicio registro del automotor
ritaalediaz/2doCuatrimestre pull request #1
Opened 2024-10-01 12:55 UTC by ritaalediaz

2024-10-01 19:14 UTC, SofiZ2001 requested changes
Algunos comentarios Rita! Avisame cualquier cosa

2024-10-01 19:14 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +    estaAgregado: any;
De qué tipo es esta variable? Agregar el modificador de acceso tambien!

2024-10-01 19:14 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +    vehiculo: any;
De qué tipo es esta variable? Agregar el modificador de acceso tambien!

2024-10-01 19:14 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +    agregarVehiculo(vehiculo: Vehiculo) {
Agregar el modificador de acceso

2024-10-01 19:14 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +  /*  // Modificar un vehiculo.
Eliminar codigo comentado si no lo vas a utilizar

2024-10-01 19:14 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +
Falta funcionalidad de modificarVehiculo

2024-10-03 13:10 UTC, SofiZ2001 requested changes
Mas comments!

2024-10-03 13:10 UTC, SofiZ2001 commented on registroAutomotor/Vehiculo.ts
> +    static getModelo() {
getModelo debería ser un metodo publico, no estatico! Ademas moverlo de lugar hacia abajo de los atributos para mejor legibilidad de codigo!

2024-10-03 13:10 UTC, SofiZ2001 commented on registroAutomotor/Vehiculo.ts
> +        throw new Error("Method not implemented.");
Esta bien que lance un error esta funcion?

2024-10-03 13:10 UTC, SofiZ2001 commented on registroAutomotor/Vehiculo.ts
> +    setlistaVehiculo(listaVehiculo: Vehiculo[]) {
No estoy segura para que sirva esta funcion en la clase Vehiculo, ya tenes el setListaVehiculo en RegistroAutomotor!

2024-10-03 13:10 UTC, SofiZ2001 commented on registroAutomotor/RegistroAutomotor.ts
> +             vehiculo.setlistaVehiculo(this.listaVehiculo);
En realidad el modificar no debería modificar la lista entera, sino un vehiculo en especifico. Deberías poder encontrar primero el vehiculo que queres modificar (parecido a como hiciste con eliminar) y luego hacer la modificacion.
Dos tip:

- En la busqueda del vehiculo, podes saber si es el que necesitas preguntando por alguna variable con un valor que solo ese vehiculo tenga. Ej las patentes para los autos, los dnis para las personas, etc. Una vez que encuentra el vehiculo con la patente que le pasaste, haces la modificacion

- Una vez obtenido el vehiculo simplemente para modificarlo haces uso de los metodos set para cambiar los atributos que vos quieras. (Ej setMarca, setModelo, etc.)

Obviamente es una forma de hacerlo pero no la única! Fijate si te sirve :D

2024-10-03 13:47 UTC, ritaalediaz commented on registroAutomotor/Vehiculo.ts
> +    static getModelo() {
ahh me dio error algo y viste que te pone opciones para correjir? y le mande... no me di cuenta xq yo no lo habia puesto jajja ahora me fijo gracias sofi...ahora voy a tener en cuenta todo eso

2024-10-09 02:43 UTC, SofiZ2001 requested changes
2 comments

2024-10-09 02:43 UTC, SofiZ2001 commented on regAutomotorHerencia/moto.ts
> +}
Deberias agregarle alguna función/atributo que sea unica de esta clase para que tenga sentido la herencia

2024-10-09 02:43 UTC, SofiZ2001 commented on regAutomotorHerencia/camion.ts
> +}
Deberias agregarle alguna función/atributo que sea unica de esta clase para que tenga sentido la herencia

2024-10-10 00:17 UTC, SofiZ2001 approved these changes
LG2M

2024-10-15 00:51 UTC, SofiZ2001 approved these changes
LG2M

2024-10-21 18:07 UTC, merged