tercer entregable
ritaalediaz/2doCuatrimestre pull request #3
Opened 2024-10-22 18:51 UTC by ritaalediaz

2024-10-23 14:05 UTC, SofiZ2001 requested changes
Algunos comments!

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/caballero.ts
> +        console.log(`${this.nombre} se protege con su escudo potente.`);
faltan modificadores de acceso en las funciones

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/ladydi.ts
> +export class ladydi extends Personajes {
Por convencion los nombres de las Clases siempre empiezan con mayuscula

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/mago.ts
> + export class mago extends Personajes {
Por convencion los nombres de las Clases siempre empiezan con mayuscula

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/juego.ts
> +      });
modificadores de acceso

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/ladydi.ts
> +      }
modificadores de acceso

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/mago.ts
> +    }
modificadores de acceso

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/verdugo.ts
> +export class verdugo extends Personajes {
Por convencion los nombres de las Clases siempre empiezan con mayuscula

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/verdugo.ts
> +      }
modificadores de acceso

2024-10-23 14:05 UTC, SofiZ2001 commented on videoJuego/main.ts
> +
Te esta faltando la parte de crear la "evolucion" de un personaje. Ejemplo teniendo la clase mago, podrías tener un MagoLegendario

2024-10-23 18:10 UTC, SofiZ2001 requested changes
te quedaron 2 comments pendientes

2024-10-23 19:11 UTC, ritaalediaz commented on videoJuego/mago.ts
> + export class mago extends Personajes {
moficicado

2024-10-23 19:11 UTC, ritaalediaz commented on videoJuego/juego.ts
> +      });
modificado

2024-10-23 19:11 UTC, ritaalediaz commented on videoJuego/ladydi.ts
> +      }
modificado.

2024-10-23 19:12 UTC, ritaalediaz commented on videoJuego/verdugo.ts
> +export class verdugo extends Personajes {
modificacion realizada

2024-10-23 19:12 UTC, ritaalediaz commented on videoJuego/main.ts
> +
modificacion realizada.

2024-10-23 23:56 UTC, SofiZ2001 requested changes
Un mini comment mas

2024-10-23 23:56 UTC, SofiZ2001 commented on videoJuego/magoMejorado.ts
> + export class MagoMejorado extends Personajes {
MagoMejorado es un Mago tambien o no? Deberia heredar de Mago, que a su vez este mismo hereda de Personaje :)

2024-10-24 18:37 UTC, ritaalediaz commented on videoJuego/magoMejorado.ts
> + export class MagoMejorado extends Personajes {
modificacion realizada.

2024-10-24 18:57 UTC, SofiZ2001 approved these changes
LG2M

2024-10-24 23:38 UTC, merged